version: '3.7'

services:
  poc.graphql.api:
    image: ${DOCKER_REGISTRY-}pocgraphqlapi
#    volumes:
#      - db-scripts:/migrations
#    container_name: poc-graphql-api
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: Poc.GraphQl.Api/Dockerfile
#    restart: on-failure

#  poc.graphql.db:
#    image: ${DOCKER_REGISTRY-}pocgraphqldb
#    volumes:
#      - db-scripts:/migrations
#    container_name: poc-graphql-db
#    ports:
#     - "3306:3306"
#    build:
#      context: .
#      dockerfile: Poc.GraphQl.Api/MySqlDockerfile
#    depends_on:
#      - poc.graphql.api
#    healthcheck:
#      test: ["CMD", "curl", "-sSf", "http://localhost:5000/api/values"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    command: ["./wait-for-it.sh", "--timeout=30", "poc.graphql.api:5000", "--", "echo 'Yo'"]

#volumes:
#  db-scripts: